### ISSUE TITLE
Visibility of video controls

### ISSUE THREAD

**Issue by jancborchardt** [Instagit/videojs-sublime#10]
The controls have a very low to no visibility on light or white backgrounds / movies. To alleviate that we should do it like Youtube or Twitch, just add a gradient behind which goes from half-transparent black on the bottom to fully transparent a bit up. This improves the visibility a lot.

**Comment by Instagit** [comment]
Added a gradient in da023467e5073a1d07b30e9fb589e6d9fc10ce67. It's almost invisible during normal playback, but enough to see the controls on light backgrounds.

![gradient](https://cloud.githubusercontent.com/assets/2681794/11069977/5bccfc7e-87d9-11e5-88bf-16ca45f8cf8b.png)

**Comment by jancborchardt** [comment]
@Instagit great stuff! That’s exactly what I meant.
