### ISSUE TITLE
Look of close button

### ISSUE THREAD

**Issue by jancborchardt** [Instagit/videojs-sublime#11]
The close button right now has a very iOS / GNOME like style. Instead it should look similar as in our Gallery app. Just use the class `.icon-view-close` and you’ll get the correct icon from core. :)

**Comment by Instagit** [comment]
![close-icon](https://cloud.githubusercontent.com/assets/2681794/11041991/f2b7452e-8714-11e5-91ba-1a360fda693c.jpg)

For now I made it like this. The close icon is shown with low opacity and the opacity increases on mouseover. Will be in the next update.

I'll try to make the button fade out with the rest of the Video.js UI elements later on.

**Comment by jancborchardt** [comment]
@Instagit you’re awesome! :) Looks really good now.
