### ISSUE TITLE
Support for older browsers

### ISSUE THREAD

**Issue by jancborchardt** [Instagit/videojs-sublime#12]
With the current videoviewer we use [Mediaelement.js](http://mediaelementjs.com/) – they have fallbacks using Silverlight and Flash for older browsers. Is this also possible with video.js? @Instagit 

cc @VicDeo who is the main dev of our current [files_videoviewer](https://github.com/owncloud/apps/tree/master/files_videoviewer), alos cc @LukasReschke because he mentioned that.

**Comment by Instagit** [comment]
Yes, video.js has flash fallback, too, but I didn't include that so far. I'll include it when I upgrade video.js to the latest version -> https://github.com/Instagit/videojs-sublime/issues/8

**Comment by jancborchardt** [comment]
Great stuff!

**Comment by Instagit** [comment]
Upgrading to the latest Video.js version completely breaks the current CSS (https://github.com/cabin/videojs-sublime-skin/issues/12). It has a lot of small improvements, but nothing essential as far as I can see, so I'd suggest to stay at this version for now.

I just saw that the flash fallback is actually included, so now we have to find out if it works or why it doesn't. I'm going to do some testing later today.

**Comment by jancborchardt** [comment]
@Instagit awesome! Are you based in Germany btw? If you’re near Stuttgart, Munich or Berlin we could hack together some time. :)

**Comment by Instagit** [comment]
Yes, I work in/live near Hamburg. :)

**Comment by jancborchardt** [comment]
Nice! Then definitely you should plan to attend the ownCloud conference in Berlin next year: https://owncloud.org/conf/ :) It will likely be either end of August or mid September.

Also, I’m originally from between Hannover and Osnabrück so when I’m back there sometimes we could also hack a bit. :)

**Comment by Instagit** [comment]
Cool, I'll keep it in mind!

**Comment by Instagit** [comment]
As for flash support: I tested it in IE8 with the [fix-video-link](https://github.com/Instagit/videojs-sublime/tree/fix-video-link) branch and it works, but it's not a good experience as IE8 lacks support for many of the CSS features used to make the player responsive and the page looks very broken. Same with IE9 by the way.

**Comment by jancborchardt** [comment]
@Instagit it doesn’t need to look pretty in IE8/9 or work on mobile, as long as basic video playback works. :)

**Comment by Instagit** [comment]
The player is designed to work on mobile with current browsers, so that should not be a problem - otherwise I need to fix it :)

But to give you an idea how unusable it is in IE8 and IE9, here are some screenshots:

IE8:
![ie8](https://cloud.githubusercontent.com/assets/2681794/11114141/b0be2e48-8922-11e5-9f69-ac5426d768d5.jpg)

IE9:
![ie9](https://cloud.githubusercontent.com/assets/2681794/11114143/b46d4a24-8922-11e5-931d-99dcfb267840.png)

With MS Edge out, I'm not looking to support Internet Exploder, especially old versions (IE 8,9 and 10 combined have about 5% market share globally), but if it's required by ownCloud we'd definitely have to add browser detection and separate CSS.

**Comment by jancborchardt** [comment]
@Instagit Ok, IE8 looks ok, if the video is playable. :) IE9 we should maybe fix a bit.

Unfortunately the 5% market share is not fully correct, see https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0 ;) (StatCounter checks by traffic, NetMarketShare by unique user. So it’s likely something inbetween like 10–15%.) But we @owncloud/designers will probably be able to help so we can make sure this awesome video app works nicely. :)

**Comment by jancborchardt** [comment]
But yeah again – on IE8/9/10 bare functionality is ok, just playing videos. Doesn’t need to look great and mobile support is not needed there either of course.

**Comment by Instagit** [comment]
Ok. Do you know if ownCloud provides a way for apps to get the browser version? If not, I'd build a very basic JS detection for IE and load another CSS file with a simple player. I don't want to include any extra libraries for this.

**Comment by jancborchardt** [comment]
Yeah, we have an IE detection which for example is used by our fixes.css: https://github.com/owncloud/core/blob/master/core/css/fixes.css

cc @MorrisJobke for more info – do we have documentation on how to use this?

**Comment by Instagit** [comment]
Ok, looks like normal IE detection that adds classes to the HTML tag. That should do, thanks!

**Comment by MorrisJobke** [comment]
> cc @MorrisJobke for more info – do we have documentation on how to use this?

Sadly not.

**Comment by Instagit** [comment]
Fixed in https://github.com/Instagit/videojs-sublime/commit/7dfeb5d622ec6d62e503e4462eb1bf4ca8c5582f.

The player is now centered at the top in IE8 and IE9 with different CSS, because they don't support transform. IE8 uses Flash fallback and the controls are hidden as they don't work.

**Comment by jancborchardt** [comment]
@Instagit awesome! :) Sounds like we could potentially switch to this video player for ownCloud 9.0. What do you think @VicDeo?

**Comment by VicDeo** [comment]
if that's ok https://github.com/Instagit/videojs-sublime/issues/12#issuecomment-156790978
I would not mind

**Comment by jancborchardt** [comment]
Yes, Apache 2 is compatible with AGPL v3: https://www.gnu.org/licenses/license-list.en.html#apache2
