### ISSUE TITLE
Videos not playing in some browsers

### ISSUE THREAD

**Issue by Instagit** [Instagit/videojs-sublime#16]
Many videos don't play in Chrome or Safari.

I think this might just be a matter of using the right URL to access them (webdav link instead of the one the player is using now).

**Comment by MorrisJobke** [comment]
> I think this might just be a matter of using the right URL to access them (webdav link instead of the one the player is using now).

Ah yes...webdav is always better :)

**Comment by Instagit** [comment]
Ok, I created a [new branch](https://github.com/Instagit/videojs-sublime/tree/fix-video-link) that fixes the playback in Chrome.

Since I don't know much about the file functions in ownCloud I pretty much copy/pasted this from the official video player app and it works, but it would be nice if someone could take a look at it and confirm that this is the right way to do it.

/cc @VicDeo @jancborchardt 

One small issue though: There's no error message when trying to play a file with a supported format (H264/MP4) encoded with an unsupported profile. For example [this video](http://www.sample-videos.com/video/mp4/360/big_buck_bunny_360p_10mb.mp4).

**Comment by jancborchardt** [comment]
@instagit if it can not be displayed, just use the ome error message there is. :)

Also cc @oparoz regardong testing the video player component, since we should merge it into Gallery.

**Comment by Instagit** [comment]
I merged fix-video-link into master, because even with the outstanding issue it's definitely an improvement.

**Comment by jancborchardt** [comment]
Yeah, good call. :)
