### ISSUE TITLE
»This app has no minimum ownCloud version assigned. This will be an error in ownCloud 11 and later.«

### ISSUE THREAD

**Issue by jancborchardt** [Instagit/videojs-sublime#21]
@Instagit what’s the minimum ownCloud version the app runs on? It should be defined in the info.xml. :)

**Comment by Instagit** [comment]
><require>8.1.1</require>

https://github.com/Instagit/videojs-sublime/blob/master/appinfo/info.xml#L16

I put the current ownCloud version in there when I started developing the app, but I think it might not be compatible with that version anymore.

**Comment by jancborchardt** [comment]
It’s an old syntax though. See https://github.com/owncloud/core/pull/21808/files#diff-fea49f0732d061e089d5ce81b2483176L10 on how the syntax needs to be :)

**Comment by Instagit** [comment]
I'll update it with the current version unless someone wants to do compatibility testing for old ownCloud versions. :wink:

**Comment by jancborchardt** [comment]
@Instagit yeah, but please use the new format, and also assign a max version. The max version should be the current dev version, which is 9.0.

**Comment by jancborchardt** [comment]
```
<dependencies>
    <owncloud min-version="8.2" max-version="9.0" />
</dependencies>
```

**Comment by Instagit** [comment]
Ok, changed it. Is that a requirement for default apps? According to [the documentation](https://doc.owncloud.org/server/9.0/developer_manual/app/info.html) "requiremin" should be enough.

**Comment by jancborchardt** [comment]
Seems like that documentation page needs to be updated maybe? cc @DeepDiver1975
