### ISSUE TITLE
mov file support

### ISSUE THREAD

**Issue by jancborchardt** [Instagit/videojs-sublime#7]
Is it possible to support the playback of mov? Or is that in some way proprietary?

**Comment by Instagit** [comment]
MOV support depends on the browser. I think Firefox and Safari can play it, Chrome can't. I enabled support for MOV files, because users asked for it, but the playback will fail in Chrome and I don't think I can do something about that.

**Comment by jancborchardt** [comment]
Ah, alright. Yeah, it works in FF but not in Chrome.

**Comment by jancborchardt** [comment]
@CorneelDragon good point! :) Could you open a separate new issue for that? Thanks a lot! :)
