### ISSUE TITLE
Update videojs to 5.0.0

### ISSUE THREAD

**Issue by MorrisJobke** [Instagit/videojs-sublime#8]
I just tested this app and it works nicely. Beside the fact that it can't play a mp4 file in safari (whereas it worked just fine in Chrome). I checked http://praegnanz.de/html5video/p_videojs.php as demo video and it works in safari just fine.

Then I noticed that this app ships a videojs version 4.1.x ...maybe an upgrade to 5.0.0 could solve the issue.

**Comment by Instagit** [comment]
Most MP4 files have actually stopped working for me in Chrome with the ownCloud 8.2.0 update. Including the latest videojs version is definitely a good idea, I'll try it asap and see if it improves things.

**Comment by MorrisJobke** [comment]
Nice :) Thanks :)

**Comment by Instagit** [comment]
I just checked and upgrading to video.js 5.0.0 doesn't seem to help with video playback. It does however make the current CSS unusable (https://github.com/cabin/videojs-sublime-skin/issues/12).

So for now I don't see a benefit from upgrading to Video.js 5.0.0.

**Comment by MorrisJobke** [comment]
> Could you link to the video that doesn't work in Safari?

Sadly none that I want to link here. And all other mp4 all also doesn't work in chrome :( Maybe I can find some in the next days

**Comment by Instagit** [comment]
Ok, I'll start looking for the problem with Chrome then. Maybe that also solves the Safari problems.
